Preprocess and precompute with multiprocessing
attilanagy234/syntax-augmentation-nmt pull request #85
Opened 2022-08-31 13:00 UTC by dorinapetra

- use general precompute in script
- preprocess and precompute at the same time
- preprocess and precompute can use multiprocessing

2022-08-31 14:44 UTC, attilanagy234 requested changes
Great job 🔥 All looks good, but could we add a test for the preprocess_and_precompute method? Using some dummy data is totally fine, just to see that both the preprocessing and the dep tree precomputation works.

2022-09-01 08:00 UTC, Baaart25 approved these changes
I found some nice to fix things

2022-09-01 08:10 UTC, dorinapetra commented on src/hu_nmt/test/preprocessor/preprocessor_test.py
> -    def test_contains_one_sentence_true(self):
I restored them

2022-09-01 13:23 UTC, attilanagy234 approved these changes
Looking good now, thanks for making the changes

2022-09-01 13:33 UTC, merged